void print_cmd_usage();
int init_modules(int argc, const TSDCHAR* argv[]);
int load_modules();
void free_modules();

void set_stream_stats_mbps(const double);
void add_stream_stats_total_bytes(const int);

void **do_pgoutput_create(const TSDCHAR *fname, const proginfo_t *pi, ch_info_t *ch_info, const int actually_start);
void do_pgoutput(void **modulestats, unsigned char *buf, size_t size);
int do_pgoutput_check(void **modulestats);
int do_pgoutput_wait(void **modulestats);
int do_pgoutput_changed(void **modulestats, const proginfo_t *old_pi, const proginfo_t *new_pi);
void do_pgoutput_end(void **modulestats, const proginfo_t *pi);
void do_pgoutput_close(void **modulestats, const proginfo_t *pi);
int do_postconfig();
void do_close_module();
void do_open_stream();
void do_encrypted_stream(unsigned char *buf, size_t size);
void do_stream(unsigned char *buf, size_t size, int encrypted);
void do_close_stream();
void do_tick(int64_t);
int do_stream_generator_open(void **param, ch_info_t *chinfo);
void do_stream_generator(void *param, unsigned char **buf, int *size);
void do_stream_generator_cnr(void *param);
void do_stream_generator_siglevel(void *param);
void do_stream_generator_close(void *param);
void do_stream_decoder(void *param, unsigned char **dst_buf, int *dst_size, const unsigned char *src_buf, int src_size);
int do_stream_decoder_open(void **param, int *);
int do_stream_generator_wait(void *param, int timeout_ms);
int is_implemented_stream_decoder_stats();
void do_stream_decoder_stats(void *param);
void do_stream_decoder_close(void *param);
void do_message(const TSDCHAR *modname, message_type_t msgtype, tsd_syserr_t *err, const TSDCHAR *msg);
const TSDCHAR *do_path_resolver(const proginfo_t *proginfo, const ch_info_t *ch_info);